#Se recomienda confirar los secretos con external secrets helm v5

variables:
  own:
    config:
      - name: "KAFKA_TOPIC"
        value: ""
      #Kafka Configurations
      - name: "TRE_KAFKA_SERVER"
        value: "pkc-56d1g.eastus.azure.confluent.cloud:9092"
      - name: "TRE_KAFKA_TOPIC_TRANSACTIONAL"
        value: "tre_tpc_sp_logs-trx_dev"
      - name: "MY_FIELDS_TO_OBFUSCATE"
        value: "(code) | (identifier)"
      - name: "LOG_OBFUSCATION_ENABLED"
        value: "true"
      - name: "TRE_KAFKA_TOPIC_AUDITOR"
        value: "tre_tpc_sp_logs-aud_dev"
    secret:
      - name: KAFKA_USER
        location: "CELL-KAFKA-USER"
      - name: KAFKA_PASSWORD
        location: "CELL-KAFKA-PASSWORD"
      - name: ONB_KAFKA_SECRET
        location: ONB-KAFKA-SECRET
      - name: ONB_KAFKA_USERNAME
        location: ONB-KAFKA-USERNAME

  common:
    config:
      - name: "ENVIRONMENT"
    secret: {}

global:
  environment: "development"
  replicaCount: "1"
  revisionHistoryLimit: "5"
  minReadySeconds: "0"
  version: "v1"

container:
  project: "development"
  registry: "gcr.io"
  tag: "2019.11.25-16.30.32"
  pullPolicy: "IfNotPresent"
  imagePullSecrets:
    - name: secret-acr
  livenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 12
  readinessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - |
          if [ "$(curl -s http://localhost:8080/actuator/health | cut -d "{" -f 2 | cut -d "}" -f 1 | cut -d "," -f 1 )" != '"status":"UP"' ];then exit 1; fi
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 12
  resources:
    requests:
      cpu: 25m
      memory: 384Mi
    limits:
      #cpu: 250m
      memory: 768Mi
  port:
    - name: msa-port
      servicePort: 80
      containerPort: 8080
      protocol: TCP
  volumeMounts:
    - name: init-sh
      mountPath: /opt/build/init.sh
      subPath: init.sh

hpa:
  minReplicas: 1
  maxReplicas: 1
  targetMemory: 768Mi

pdb:
  minAvailable: 1

volumes:
  - name: init-sh
    configMap:
      name: configMap-${project.projectName}
      items:
        - key: init.sh
          path: init.sh